### ISSUE TITLE
system requirements on github repo

### ISSUE THREAD

**Issue by pr4deepr** [lys-devel/lys#11]
Could you state system requirements in the Github repo? 
I am using a windows machine and although I have WSL, not everyone will. 

As part of JOSS review: https://github.com/openjournals/joss-reviews/issues/5869

**Comment by lys-devel** [comment]
Thank you for the comment.
I added the statements regarding system requirements in the [top page](https://github.com/lys-devel/lys).
For maintainability, the detailed system requirements are described only in the [installation page](https://lys-devel.github.io/lys/install.html).

**Comment by pr4deepr** [comment]
Thanks!
Could you add operating system info as well?

**Comment by pr4deepr** [comment]
Its a minor request.. otherwise i'm happy with this.
