### ISSUE TITLE
Statement of need of the JOSS manuscript

### ISSUE THREAD

**Issue by lys-devel** [lys-devel/lys#16]
The modification of statement of need is raised in openjournals/joss-reviews#5869.

> For the statement of need, I feel it needs a further justification of why research scientists can't just rely on the already exisiting domain-specific software tools for data analysis and visualization.

**Comment by lys-devel** [comment]
@ziatdinovmax, I added the sentences to justify the above points in line 22-32 in the [new manucript](https://github.com/openjournals/joss-papers/blob/joss.05869/joss.05869/10.21105.joss.05869.pdf).
I thank you for the comments, and I hope these modifications meet the publication criteria in JOSS.

**Comment by ziatdinovmax** [comment]
Looks good - thank you for addressing my concerns.
