### ISSUE TITLE
How to load proprietary format data

### ISSUE THREAD

**Issue by lys-devel** [lys-devel/lys#17]
The suggesting regarding the loading proprietary format data is raised in openjournals/joss-reviews#5869.

>I think currently it doesn't account for a pretty common situation when multi-dimensional data is in a proprietary format, and one needs to use some form of a translator to convert it to lys-readable format. This seems like the first and most important step without which one cannot use this package. I suggest mentioning it and perhaps providing links to some common translator packages.

**Comment by pr4deepr** [comment]
@ziatdinovmax, do you think this can be addressed by having an example in the 'examples gallery'. similar to [this](https://lys-devel.github.io/lys/tutorials/cells3d.html) ?
Also, would you have any suggestions on a proprietary data format to use?

**Comment by lys-devel** [comment]
@ziatdinovmax, I made examples to translate several format data in [documents](https://lys-devel.github.io/lys/tutorials/load_examples.html).
If you think there is another important format to be adressed, please let me know.

**Comment by ziatdinovmax** [comment]
Looks great! Thank you for taking the time to address this.
