### ISSUE TITLE
The formula for residual sum in FittingCUI

### ISSUE THREAD

**Issue by mirrormatrix** [lys-devel/lys#2]
The current formula for residual sum in lys/fitting/FittingCUI.py (line 72-75) appears to be:
```
def residualSum(self):
    data, _, _ = self.__getDataForFit()
    fitted = self.fittedData()
    return np.sqrt(np.sum(abs(data - fitted.data)**2)) / len(data)
```
where the square root is taken before the sum is divided by its length, making the calculated residual sum inaccurate.

I think by adjusting the position of the brackets as below, the formula can give the accurate residual sum.
```
def residualSum(self):
    data, _, _ = self.__getDataForFit()
    fitted = self.fittedData()
    return np.sqrt(np.sum(abs(data - fitted.data)**2) / len(data))
```
I'm looking forward to your consideration.

**Comment by lys-devel** [comment]
@mirrormatrix Thank you for the comment. I have fixed the problem.
