### ISSUE TITLE
unittest throws "FileNotFoundError"s

### ISSUE THREAD

**Issue by kuadrat** [lys-devel/lys#3]
Following [the instructions in the documentation](openjournals/joss-reviews/issues/5869), I carry out:
```
python -m unittest discover
```
in the `lys` code directory.

This results in an infinite loop of Traceback printed on console, at the core of which seems to be a `FileNotFoundError` to the file `lys/.lys/debug.log`.

Any idea what could be done to get the unittest to run as intended?

Part of openjournals/joss-reviews/issues/5869.

**Comment by lys-devel** [comment]
Thank you for the comment. I have fixed the problem.
Could you confirm that the unittest works properly?

**Comment by kuadrat** [comment]
I have confirmed that `pytest` according to the new instructions [here](https://lys-devel.github.io/lys/tutorials/test.html) work as described (except for a couple of DeprecationWarnings regarding "invalid escape sequences" (\p, \e)).
