### ISSUE TITLE
"State of the field" missing

### ISSUE THREAD

**Issue by kuadrat** [lys-devel/lys#6]
According to the JOSS guidelines [a discussion of the state of the field is required](https://joss.readthedocs.io/en/latest/review_checklist.html#software-paper) in the submitted paper.

Comparing the pros and cons of `lys` to other existing software with similar functionality would not only check this box, but also help a reader of the documentation or the paper understand better what `lys` can and cannot do. As such, I believe that the [landing page of the `lys` documentation](https://lys-devel.github.io/lys/index.html) could also benefit from such a discussion.

Suggested related software solutions that came to mind when reading about and using `lys`:
- IGOR Pro: mature system for mixed GUI and CUI multidimensional data analysis. Not open-source.
- [data-slicer](github.com/kuadrat/data-slicer) (of which I am the author): Multidimensional data inspection and analysis framework with the GUI + CUI tool `pit`. Leans more on the CUI side and is more geared towards quick data inspection rather than data analysis and creation of quality figures.
- pyqtgraph: The underlying library for many of `lys`' and `data-slicer`s functionality. No GUI, requires at least intermediate python knowledge.

Part of https://github.com/openjournals/joss-reviews/issues/5869.

**Comment by lys-devel** [comment]
Thank you for the comment.
Following your suggestion, I added "state of the field" in the manuscript (last paragraph in `Overview` section). I also changed `Statement of need` (line 22-25, 29-31 in the new manuscript)

In addition, I also added the comparison between lys and other software in [landing page](https://lys-devel.github.io/lys/index.html). I appreciate your suggestion because it greatly benefits to readers and users of `lys`.

**Comment by lys-devel** [comment]
Thank you for the fruitful comment.
- I mention advantages of open source software in the manuscript (line 99) and [document](https://lys-devel.github.io/lys/index.html). 
- I added the screenshot in [README](https://github.com/lys-devel/lys) and [document](https://lys-devel.github.io/lys/index.html).
- I also added statements regarding the target audience in the manuscript (line 50).
